version: "3.1"

services:
  api:
    image: ${REGISTRY}votingapp-api:${TAG}
    ports:
      - "80:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_API=admin:changeit@eventstore:2113
  
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
